Validation modal
anamanoilo/wallet-react-project pull request #47
Opened 2022-05-15 15:46 UTC by IronHedgehog

fix modal

2022-05-15 18:21 UTC, anamanoilo requested changes
ще мене хвилює валідаційна схема, там стоїть максимальний amount 1000000000. я думаю, що може варто по кількості символів перевіряти, а не  по максимальному числу. ну або хоча б нормальні повідомлення показувати юзеру. 
також там є  "comment: Yup.string("Comment is required")", але коментар не обовязково залишати. не розумію, до чого цей рядок.  і ще поле коментарів приймає лише літери, на це нема перевірки.  і нема стилів для помилки, якщо неправильний коментар вводиш.
також коли обираєш категорію витрати, то вона не стає чорною в формі, а лишається кольору плейсхолдера.

2022-05-15 18:21 UTC, anamanoilo commented on src/components/ModalAddTransaction/ModalAddTransaction.jsx
> +import { TextField } from "@material-ui/core";
де використовується цей TextField? для чого імпортувати?

2022-05-15 18:21 UTC, anamanoilo commented on src/components/ModalAddTransaction/ModalAddTransaction.jsx
> +                    value={values.amount.toFixed(2)}
не працює, якщо клікнути в кінець плейсхолдера і почати друкувати. нічого не записується

2022-05-16 06:21 UTC, IronHedgehog commented on src/components/ModalAddTransaction/ModalAddTransaction.jsx
> +                    value={values.amount.toFixed(2)}
то в тому і фішка, що треба писати до коми,я тому і питав, що це працює саме як треба,топорно але як треба інші методи менш топорні але можуть баганути,потещу

2022-05-16 06:52 UTC, merged